# spring配置
spring:
  application:
    name: provider-opportunity-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/npms?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&useUnicode=true&allowMultiQueries=true
    username: root
    password: xsb19991109


mybatis-plus:
  mapper-locations: classpath:com/neu/opportunitymanagement/management/mapper/*.xml
  type-aliases-package: com.neu.opportunitymanagement.management.entity
