server:
  port: 8081

# spring配置
spring:
  application:
    name: provider-opportunity-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/npms?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&useUnicode=true&allowMultiQueries=true
    username: root
    password: xsb19991109

#  redis:
#    port: 6379
#    host: http://123.56.170.249
#    database: 0
#    password: 123456


mybatis-plus:
  mapper-locations: classpath:com/neu/opportunitymanagement/oppManagement/mapper/*.xml
  type-aliases-package: com.neu.opportunitymanagement.oppManagement.entity,com.neu.opportunitymanagement.oppManagement.dto


logging:
  level:
    com.neu.opportunitymanagement: debug
